dialect = "uk"

enter_accept = true

keymap_mode = "vim-insert"

sync_address = "https://atuin.hogs.tswn.us"

update_check = false

[stats]
common_subcommands = [
  "apt",
  "cargo",
  "chezmoi",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "jj",
  "just",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "ujust",
  "yarn",
]

[sync]
records = true
